name: Build and Release

on:
  push:
    tags: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: dnf install -y fennel make

    - name: Build
      run: make

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: fishscript
